# Generated by Django 2.0 on 2018-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('openning', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.IntegerField(default=0.0)),
                ('pe_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('eps', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('one_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
